FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

# Set up a tools dev directory
WORKDIR /home/dev

# pull the gcc-arm-none-eabi tarball
RUN apt-get update \
	&& apt-get install -y wget git bzip2 cmake ninja-build python3-pip \
	&& wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 \
    && tar xvf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 \
    && rm gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2 \
	&& apt-get remove -y wget bzip2 gcc make build-essential \
	&& apt-get autoremove -y && apt-get clean -y \
	&& rm -rf /usr/lib/gcc \
    && mv /home/dev/gcc-arm-none-eabi-9-2020-q2-update/bin/* /usr/bin \
    && mv /home/dev/gcc-arm-none-eabi-9-2020-q2-update/lib/* /usr/lib \
    && rm -rf /home/dev/gcc-arm-none-eabi-9-2020-q2-update/share/doc \
    && mv /home/dev/gcc-arm-none-eabi-9-2020-q2-update/share/gcc-arm-none-eabi /usr/share \
    && mv /home/dev/gcc-arm-none-eabi-9-2020-q2-update/arm-none-eabi /usr

RUN pip3 install 'lager-cli==0.1.97'

# Set up the compiler path
ENV PATH $PATH:/home/dev/gcc-arm-none-eabi-9-2020-q2-update/bin
ENV GNU_INSTALL_ROOT /home/dev/gcc-arm-none-eabi-9-2020-q2-update/bin
ENV GNU_PREFIX arm-none-eabi

WORKDIR /app
